server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_app
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect